source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LaunchCountManager_Example', :exclusive => true do
  pod "LaunchCountManager", :path => "../"
end

target 'LaunchCountManager_Tests', :exclusive => true do
  pod "LaunchCountManager", :path => "../"

  pod 'Quick', '0.8.0'
  pod 'Nimble', '3.0.0'
end
